AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Max: 120

Layout/IndentationWidth:
  Width: 2

Style/Documentation:
  Enabled: false
